version: "3.8"

services:
  app:
    build: .
    ports:
      - "4000:4000"
    depends_on:
      - db
  db:
    image: "postgres:13"
    environment:
      POSTGRES_USER: "username"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "dbname"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
